---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake(intake)
	classify(classify)
	file_document(file_document)
	human_review(human_review)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake;
	classify -.-> file_document;
	classify -.-> human_review;
	intake -.-> classify;
	intake -.-> human_review;
	file_document --> __end__;
	human_review --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
