---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake(intake)
	tsb(tsb)
	diagrams(diagrams)
	procedure(procedure)
	parts(parts)
	warranty(warranty)
	warranty_approval(warranty_approval)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake;
	diagrams --> procedure;
	intake -.-> __end__;
	intake -.-> diagrams;
	intake -.-> tsb;
	parts --> warranty;
	procedure --> parts;
	tsb --> procedure;
	warranty -.-> finalize;
	warranty -.-> warranty_approval;
	warranty_approval --> finalize;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
