"""Semantic layer over the gold credit mart: governed measures only, no raw SQL.

``get_measure(name, grain, filters, dry_run)``:
* ``name`` must be a registered measure, ``grain`` one of its grains, ``filters`` only known
  keys; ``borrower_id`` is mandatory (row-level scope). Anything else is rejected.
* ``dry_run=True`` returns the compiled plan (model, expression, filters, row estimate) so the
  caller can check it before executing. The SQL is generated by the layer, never the agent.
"""

from __future__ import annotations

import re
from typing import Any

GOLD = [  # credit_gold.borrower_financials (as of 2026-06-30)
    {
        "borrower_id": "B-100",
        "year": 2023,
        "revenue": 41.0,
        "ebitda": 6.2,
        "total_debt": 19.0,
        "interest": 1.1,
        "principal": 2.0,
    },
    {
        "borrower_id": "B-100",
        "year": 2024,
        "revenue": 45.5,
        "ebitda": 7.1,
        "total_debt": 20.5,
        "interest": 1.2,
        "principal": 2.1,
    },
    {
        "borrower_id": "B-100",
        "year": 2025,
        "revenue": 49.8,
        "ebitda": 8.0,
        "total_debt": 22.0,
        "interest": 1.3,
        "principal": 2.2,
    },
    {
        "borrower_id": "B-400",
        "year": 2024,
        "revenue": 12.0,
        "ebitda": 1.5,
        "total_debt": 6.5,
        "interest": 0.6,
        "principal": 0.9,
    },
    {
        "borrower_id": "B-400",
        "year": 2025,
        "revenue": 11.2,
        "ebitda": 1.2,
        "total_debt": 6.8,
        "interest": 0.7,
        "principal": 0.9,
    },
]
MEASURES: dict[str, dict[str, Any]] = {
    "revenue": {"expr": "SUM(revenue)", "unit": "USD m", "grains": ["year"]},
    "ebitda": {"expr": "SUM(ebitda)", "unit": "USD m", "grains": ["year"]},
    "total_debt": {"expr": "LAST(total_debt)", "unit": "USD m", "grains": ["year"]},
    "debt_service": {"expr": "SUM(interest + principal)", "unit": "USD m", "grains": ["year"]},
    "dscr": {"expr": "ebitda / debt_service", "unit": "x", "grains": ["year"]},
    "leverage": {"expr": "total_debt / ebitda", "unit": "x", "grains": ["year"]},
}
FILTER_KEYS = {"borrower_id", "year"}
SQLISH = re.compile(r"select|drop|;|--|\bor\b\s+1=1|union", re.I)
VERSION = "credit-semantic-model v3"


class SemanticError(ValueError):
    pass


def _check(name: str, grain: str, filters: dict[str, Any]) -> None:
    if name not in MEASURES:
        raise SemanticError(f"unknown measure {name!r}; allowed: {sorted(MEASURES)}")
    if grain not in MEASURES[name]["grains"]:
        raise SemanticError(f"grain {grain!r} not available for {name}")
    unknown = set(filters) - FILTER_KEYS
    if unknown:
        raise SemanticError(f"unknown filter keys {sorted(unknown)}")
    if "borrower_id" not in filters:
        raise SemanticError("borrower_id filter is mandatory (row-level scope)")
    if any(SQLISH.search(str(v)) for v in filters.values()):
        raise SemanticError("filter values must be literals (no SQL)")


def _value(row: dict[str, Any], name: str) -> float:
    ds = row["interest"] + row["principal"]
    derived = {
        "debt_service": ds,
        "dscr": row["ebitda"] / ds,
        "leverage": row["total_debt"] / row["ebitda"],
    }
    return round(derived.get(name, row.get(name, 0.0)), 2)


def get_measure(
    name: str, grain: str, filters: dict[str, Any], dry_run: bool = True
) -> dict[str, Any]:
    _check(name, grain, filters)
    years = filters.get("year")
    years = set(years) if isinstance(years, list) else {years} if years else None
    rows = [
        r
        for r in GOLD
        if r["borrower_id"] == filters["borrower_id"] and (years is None or r["year"] in years)
    ]
    if dry_run:
        return {
            "plan": {
                "semantic_model": "credit_gold.borrower_financials",
                "measure": name,
                "expression": MEASURES[name]["expr"],
                "grain": grain,
                "filters": filters,
                "estimated_rows": len(rows),
                "sql": "generated by the semantic layer at execution",
            },
            "version": VERSION,
        }
    return {
        "measure": name,
        "unit": MEASURES[name]["unit"],
        "version": VERSION,
        "values": [{"year": r["year"], "value": _value(r, name)} for r in rows],
    }
